global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'genx-platform'
    environment: 'production'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Metrics Service
  - job_name: 'metrics-service'
    static_configs:
      - targets: ['metrics-service:9090']
    metrics_path: '/metrics'
    
  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Node Exporter for host metrics (if needed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []  # Add alertmanager endpoint if needed