apiVersion: v1
kind: Service
metadata:
  name: llm-service
spec:
  selector:
    app: llm-service
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
  - name: metrics
    port: 9090
    targetPort: 9090