# genx_platform/monitoring/prometheus/web-config.yml
# Prometheus web server TLS configuration

tls_server_config:
  cert_file: /certs/server.crt
  key_file: /certs/server.key
  client_ca_file: /certs/ca.crt
  client_auth_type: VerifyClientCertIfGiven

# Optional: Basic auth can be added here
# basic_auth_users:
#   admin: $2y$10$... # bcrypt hash