# Production deployment with NVIDIA GPU support
# Usage: docker-compose -f docker-compose.yml -f docker-compose.gpu.yml up -d

version: '3.8'

services:
  metrics-service:
    # GPU support for NVIDIA
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]