# Development override - use this if you don't have NVIDIA GPU
# This file is automatically loaded by docker-compose
version: '3.8'

services:
  metrics-service:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - TELEMETRY_ENABLED=false  # Disable telemetry for local dev
    
    # Remove GPU requirements for development
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        # No GPU device_requests