# genx_platform/genx_components/microservices/metrics/docker-compose.yml
# Metrics Microservice - Standalone deployment
version: '3.8'

services:
  # Metrics Service Only
  metrics-service:
    build:
      context: ../../../  # genx_platform directory
      dockerfile: genx_components/microservices/metrics/Dockerfile
      args:
        - VERSION=${VERSION:-1.0.0}
    image: genx/metrics-service:${VERSION:-latest}
    container_name: genx-metrics-service
    hostname: metrics-service
    ports:
      - "50056:50056"  # gRPC port
      - "9091:9090"    # Prometheus metrics port (mapped to avoid conflict)
    environment:
      # Service Configuration
      - SERVICE_NAME=metrics-service
      - SERVICE_VERSION=${VERSION:-1.0.0}
      - SERVICE_PORT=50056
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      
      # gRPC Configuration
      - GRPC_MAX_WORKERS=${GRPC_MAX_WORKERS:-8}
      - GRPC_MAX_MESSAGE_LENGTH=${GRPC_MAX_MESSAGE_LENGTH:-104857600}
      - GRPC_TLS_ENABLED=${GRPC_TLS_ENABLED:-true}
      - GRPC_TLS_CERT_PATH=/certs/server.crt
      - GRPC_TLS_KEY_PATH=/certs/server.key
      - GRPC_TLS_CA_PATH=/certs/ca.crt
      
      # Telemetry Configuration (points to platform OTel collector)
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - TELEMETRY_ENDPOINT=${TELEMETRY_ENDPOINT:-http://otel-collector:4317}
      - METRICS_PORT=9090
      
      # Registry Configuration (points to platform Consul)
      - REGISTRY_ENABLED=${REGISTRY_ENABLED:-true}
      - REGISTRY_ENDPOINT=${REGISTRY_ENDPOINT:-http://consul:8500}
      
      # Service Specific Configuration
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-30}
      - BACKGROUND_COLLECTION_INTERVAL=${BACKGROUND_COLLECTION_INTERVAL:-30}
      - MODEL_STORAGE_PATH=/models
      
      # Security
      - ENABLE_AUTH=${ENABLE_AUTH:-true}
      - AUTH_TOKEN=${AUTH_TOKEN}
      
      # Rate Limiting
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-1000}
      
    volumes:
      # TLS Certificates
      - ./certs:/certs:ro
      # Model storage
      - model-data:/models:ro
      # Logs
      - ./logs:/logs:rw
      # Host system access for metrics collection (read-only)
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Disk metrics
      - /:/host/root:ro
      - /dev/disk:/dev/disk:ro
      
    networks:
      - genx-platform-network
      
    restart: unless-stopped
    
    # Security Configuration
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_PTRACE      # For process metrics
      - DAC_READ_SEARCH # For filesystem access
      - NET_RAW         # For network metrics
    
    # Resource Limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging Configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=metrics,environment=${ENVIRONMENT:-production}"
    
    # Health Check
    healthcheck:
      test: ["CMD", "python", "-m", "grpc_health.v1.health_check", "--address=localhost:50056"]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    
    # Labels for service discovery
    labels:
      com.genx.service: "metrics-service"
      com.genx.component: "genx"
      com.genx.microservice: "true"
      com.genx.port.grpc: "50056"
      com.genx.port.metrics: "9090"
      consul.service: "metrics-service"
      consul.tags: "genx,microservice,grpc,metrics"

volumes:
  model-data:
    driver: local

networks:
  genx-platform-network:
    external: true
    name: genx-platform-network