# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x04genx\"\xaf\x01\n\x10LoadModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x32\n\x06\x63onfig\x18\x04 \x03(\x0b\x32\".genx.LoadModelRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x11LoadModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"&\n\x12UnloadModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"F\n\x13UnloadModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"*\n\x16GetModelContextRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"\xdc\x01\n\x17GetModelContextResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x39\n\x06\x63onfig\x18\x05 \x03(\x0b\x32).genx.GetModelContextResponse.ConfigEntry\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\x18GenerateEmbeddingRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\r\n\x05texts\x18\x02 \x03(\t\"`\n\x19GenerateEmbeddingResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nembeddings\x18\x03 \x03(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xc5\x02\n\x13ModelContextService\x12>\n\tLoadModel\x12\x16.genx.LoadModelRequest\x1a\x17.genx.LoadModelResponse\"\x00\x12\x44\n\x0bUnloadModel\x12\x18.genx.UnloadModelRequest\x1a\x19.genx.UnloadModelResponse\"\x00\x12P\n\x0fGetModelContext\x12\x1c.genx.GetModelContextRequest\x1a\x1d.genx.GetModelContextResponse\"\x00\x12V\n\x11GenerateEmbedding\x12\x1e.genx.GenerateEmbeddingRequest\x1a\x1f.genx.GenerateEmbeddingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_GETMODELCONTEXTRESPONSE_CONFIGENTRY']._loaded_options = None
  _globals['_GETMODELCONTEXTRESPONSE_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_LOADMODELREQUEST']._serialized_start=20
  _globals['_LOADMODELREQUEST']._serialized_end=195
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_start=150
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_end=195
  _globals['_LOADMODELRESPONSE']._serialized_start=197
  _globals['_LOADMODELRESPONSE']._serialized_end=265
  _globals['_UNLOADMODELREQUEST']._serialized_start=267
  _globals['_UNLOADMODELREQUEST']._serialized_end=305
  _globals['_UNLOADMODELRESPONSE']._serialized_start=307
  _globals['_UNLOADMODELRESPONSE']._serialized_end=377
  _globals['_GETMODELCONTEXTREQUEST']._serialized_start=379
  _globals['_GETMODELCONTEXTREQUEST']._serialized_end=421
  _globals['_GETMODELCONTEXTRESPONSE']._serialized_start=424
  _globals['_GETMODELCONTEXTRESPONSE']._serialized_end=644
  _globals['_GETMODELCONTEXTRESPONSE_CONFIGENTRY']._serialized_start=150
  _globals['_GETMODELCONTEXTRESPONSE_CONFIGENTRY']._serialized_end=195
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_start=646
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_end=705
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_start=707
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_end=803
  _globals['_MODELCONTEXTSERVICE']._serialized_start=806
  _globals['_MODELCONTEXTSERVICE']._serialized_end=1131
# @@protoc_insertion_point(module_scope)
