# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_service.proto\x12\x04genx\"\xaf\x01\n\x10LoadModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x32\n\x06\x63onfig\x18\x04 \x03(\x0b\x32\".genx.LoadModelRequest.ConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"D\n\x11LoadModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"&\n\x12UnloadModelRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"F\n\x13UnloadModelResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\'\n\x13GetModelInfoRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"o\n\x14GetModelInfoResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nmodel_type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"6\n\x13GetEmbeddingRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\r\n\x05texts\x18\x02 \x03(\t\"[\n\x14GetEmbeddingResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\nembeddings\x18\x03 \x03(\x02\x12\r\n\x05\x65rror\x18\x04 \x01(\t2\xa6\x02\n\x0cModelService\x12>\n\tLoadModel\x12\x16.genx.LoadModelRequest\x1a\x17.genx.LoadModelResponse\"\x00\x12\x44\n\x0bUnloadModel\x12\x18.genx.UnloadModelRequest\x1a\x19.genx.UnloadModelResponse\"\x00\x12G\n\x0cGetModelInfo\x12\x19.genx.GetModelInfoRequest\x1a\x1a.genx.GetModelInfoResponse\"\x00\x12G\n\x0cGetEmbedding\x12\x19.genx.GetEmbeddingRequest\x1a\x1a.genx.GetEmbeddingResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._loaded_options = None
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_LOADMODELREQUEST']._serialized_start=30
  _globals['_LOADMODELREQUEST']._serialized_end=205
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_start=160
  _globals['_LOADMODELREQUEST_CONFIGENTRY']._serialized_end=205
  _globals['_LOADMODELRESPONSE']._serialized_start=207
  _globals['_LOADMODELRESPONSE']._serialized_end=275
  _globals['_UNLOADMODELREQUEST']._serialized_start=277
  _globals['_UNLOADMODELREQUEST']._serialized_end=315
  _globals['_UNLOADMODELRESPONSE']._serialized_start=317
  _globals['_UNLOADMODELRESPONSE']._serialized_end=387
  _globals['_GETMODELINFOREQUEST']._serialized_start=389
  _globals['_GETMODELINFOREQUEST']._serialized_end=428
  _globals['_GETMODELINFORESPONSE']._serialized_start=430
  _globals['_GETMODELINFORESPONSE']._serialized_end=541
  _globals['_GETEMBEDDINGREQUEST']._serialized_start=543
  _globals['_GETEMBEDDINGREQUEST']._serialized_end=597
  _globals['_GETEMBEDDINGRESPONSE']._serialized_start=599
  _globals['_GETEMBEDDINGRESPONSE']._serialized_end=690
  _globals['_MODELSERVICE']._serialized_start=693
  _globals['_MODELSERVICE']._serialized_end=987
# @@protoc_insertion_point(module_scope)
