# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'retrieval_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17retrieval_service.proto\x12\x04genx\"R\n\x14SearchVectorsRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x14\n\x0cquery_vector\x18\x02 \x03(\x02\x12\r\n\x05top_k\x18\x03 \x01(\x05\"[\n\x15SearchVectorsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12#\n\x07results\x18\x02 \x03(\x0b\x32\x12.genx.SearchResult\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x94\x01\n\x0cSearchResult\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x30\n\x07payload\x18\x03 \x03(\x0b\x32\x1f.genx.SearchResult.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32^\n\x10RetrievalService\x12J\n\rSearchVectors\x12\x1a.genx.SearchVectorsRequest\x1a\x1b.genx.SearchVectorsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHRESULT_PAYLOADENTRY']._loaded_options = None
  _globals['_SEARCHRESULT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHVECTORSREQUEST']._serialized_start=33
  _globals['_SEARCHVECTORSREQUEST']._serialized_end=115
  _globals['_SEARCHVECTORSRESPONSE']._serialized_start=117
  _globals['_SEARCHVECTORSRESPONSE']._serialized_end=208
  _globals['_SEARCHRESULT']._serialized_start=211
  _globals['_SEARCHRESULT']._serialized_end=359
  _globals['_SEARCHRESULT_PAYLOADENTRY']._serialized_start=313
  _globals['_SEARCHRESULT_PAYLOADENTRY']._serialized_end=359
  _globals['_RETRIEVALSERVICE']._serialized_start=361
  _globals['_RETRIEVALSERVICE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
