# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vector_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x04genx\"E\n\x17\x43reateCollectionRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x13\n\x0bvector_size\x18\x02 \x01(\x05\"P\n\x18\x43reateCollectionResponse\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"P\n\x14UpsertVectorsRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12!\n\x06points\x18\x02 \x03(\x0b\x32\x11.genx.VectorPoint\"\x8a\x01\n\x0bVectorPoint\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12/\n\x07payload\x18\x03 \x03(\x0b\x32\x1e.genx.VectorPoint.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"M\n\x15UpsertVectorsResponse\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xb5\x01\n\x12VectorStoreService\x12S\n\x10\x43reateCollection\x12\x1d.genx.CreateCollectionRequest\x1a\x1e.genx.CreateCollectionResponse\"\x00\x12J\n\rUpsertVectors\x12\x1a.genx.UpsertVectorsRequest\x1a\x1b.genx.UpsertVectorsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORPOINT_PAYLOADENTRY']._loaded_options = None
  _globals['_VECTORPOINT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_CREATECOLLECTIONREQUEST']._serialized_start=30
  _globals['_CREATECOLLECTIONREQUEST']._serialized_end=99
  _globals['_CREATECOLLECTIONRESPONSE']._serialized_start=101
  _globals['_CREATECOLLECTIONRESPONSE']._serialized_end=181
  _globals['_UPSERTVECTORSREQUEST']._serialized_start=183
  _globals['_UPSERTVECTORSREQUEST']._serialized_end=263
  _globals['_VECTORPOINT']._serialized_start=266
  _globals['_VECTORPOINT']._serialized_end=404
  _globals['_VECTORPOINT_PAYLOADENTRY']._serialized_start=358
  _globals['_VECTORPOINT_PAYLOADENTRY']._serialized_end=404
  _globals['_UPSERTVECTORSRESPONSE']._serialized_start=406
  _globals['_UPSERTVECTORSRESPONSE']._serialized_end=483
  _globals['_VECTORSTORESERVICE']._serialized_start=486
  _globals['_VECTORSTORESERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
