# monitoring-service/configs/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'monitoring-cluster'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load alert rules
rule_files:
  - /etc/prometheus/alerts/*.yml
  - /etc/prometheus/recording_rules/*.yml

# Scrape configurations
scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          component: 'monitoring'
          
  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
        labels:
          service: 'otel-collector'
          component: 'monitoring'
          
  # Monitoring API
  - job_name: 'monitoring-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['monitoring-api:8000']
        labels:
          service: 'monitoring-api'
          component: 'monitoring'
          
  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
          component: 'monitoring'
          
  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'
          component: 'monitoring'
          
  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'
          component: 'monitoring'
  
  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          service: 'alertmanager'
          component: 'monitoring'

  # Dynamic service discovery for microservices
  - job_name: 'microservices'
    dns_sd_configs:
      - names:
          - 'tasks.*.monitoring-network'
        type: 'A'
        port: 9090
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - source_labels: [__meta_dns_name]
        regex: 'tasks\.(.+)\.monitoring-network'
        target_label: service
        replacement: '${1}'