# genx_platform/genx_components/microservices/metrics/monitoring/alertmanager/config.yml
global:
  resolve_timeout: 5m
  smtp_from: 'alerts@genx.ai'
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'

  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
      
    # Service-specific routing
    - match:
        service: metrics-service
      receiver: 'metrics-team'
      
    # Development environment
    - match:
        environment: development
      receiver: 'dev-null'

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

# Receivers
receivers:
  - name: 'default'
    email_configs:
      - to: 'ops-team@genx.ai'
        headers:
          Subject: '[GenX Alert] {{ .GroupLabels.alertname }} - {{ .GroupLabels.severity }}'
        html: |
          <h3>Alert: {{ .GroupLabels.alertname }}</h3>
          <p><b>Severity:</b> {{ .GroupLabels.severity }}</p>
          <p><b>Summary:</b> {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}</p>
          <p><b>Description:</b> {{ range .Alerts }}{{ .Annotations.description }}{{ end }}</p>
          
  - name: 'critical'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    slack_configs:
      - channel: '#critical-alerts'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
        
  - name: 'metrics-team'
    email_configs:
      - to: 'metrics-team@genx.ai'
    slack_configs:
      - channel: '#metrics-alerts'
        title: 'Metrics Service Alert: {{ .GroupLabels.alertname }}'
        
  - name: 'dev-null'
    # Silently drop development alerts