# loki-tls-config.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  
  # TLS for external HTTP access (from Grafana, external services)
  http_tls_config:
    cert_file: /certs/server.crt
    key_file: /certs/server.key
    client_auth_type: VerifyClientCertIfGiven
    client_ca_file: /certs/ca.crt
    
  
  # No TLS for internal gRPC (within Docker network)
  # This is secure because Docker provides network isolation

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: loki  # Use service name for Docker networking
    kvstore:
      store: inmemory

# Production-grade schema with retention
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Production limits
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 100          # Increased for production
  ingestion_burst_size_mb: 200    # Increased for production
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  max_entries_limit_per_query: 5000
  max_query_series: 500
  max_query_parallelism: 32

# Retention configuration
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days

# Query performance
querier:
  max_concurrent: 20
  engine:
    timeout: 5m
    max_look_back_period: 720h

# Frontend for load balancing
frontend:
  compress_responses: true
  max_outstanding_per_tenant: 2048

# Ruler for alerts
ruler:
  alertmanager_url: https://alertmanager:9093
  enable_api: true
  enable_alertmanager_v2: true
  rule_path: /loki/rules-temp
  storage:
    type: local
    local:
      directory: /loki/rules

analytics:
  reporting_enabled: false