version: '3.8'

services:
  llm-service:
    image: ${REGISTRY}/llm-service:${VERSION:-staging}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      - ENVIRONMENT=staging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"