# genx_platform/genx_components/microservices/metrics/monitoring/promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: genx
    batchwait: 1s
    batchsize: 1048576
    external_labels:
      cluster: genx-production
      environment: ${ENVIRONMENT}

scrape_configs:
  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: '^(?P<container_name>genx-[^-]+)'
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # GenX application logs
  - job_name: genx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: genx-logs
          __path__: /genx/logs/*.log
    
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+)\s+(?P<level>\w+)\s+(?P<service>[^\s]+)\s+(?P<message>.*)$'
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      - labels:
          level:
          service:
      - metrics:
          log_lines_total:
            type: Counter
            description: "Total number of log lines"
            source: level
            config:
              action: inc
      - match:
          selector: '{level=~"ERROR|CRITICAL"}'
          stages:
            - metrics:
                errors_total:
                  type: Counter
                  description: "Total number of errors"
                  config:
                    action: inc

  # System logs
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'